### ISSUE TITLE
Failed to run diagnostics lintr

### ISSUE THREAD

**Issue by nathaneastwood** [Ikuyadeu/vscode-R#343]
**Describe the bug**
I couldn't decide if this was a `languageserver` issue or not, sorry. Every time I open a new file, the top line shows the error `Failed to run diagnostics: lintr`.

**Expected behavior**
I expect the files lints to be correctly checked and any issues display in the problems tab.

**Environment (please complete the following information):**
 - OS: macOS
 - Version: 1.45.1
    Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
    Date: 2020-05-14T08:33:47.663Z
    Electron: 7.2.4
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Darwin x64 19.4.0
 - R Version: 3.6.3
 - vscode-R version: 1.3.0
- languageserver version: 0.3.5
- lintr version: 2.0.1 

**Additional context**
I see the following in the diagnostics but I am not sure if it is related.

```
diagnostics_task: <callr_status_error: callr subprocess failed: attempt to apply non-function>
 in process 
-->
<callr_remote_error in linters[[linter]](expr):
 attempt to apply non-function>
 in process 78394 
```

I know this is all very vague, please let me know if you need any additional information.

**Comment by renkun-ken** [comment]
Do you have any `.lintr` file config to be applied to the document you are editing?

This looks most likely that something wrong with lintr package working with the document you are editing due to some subtle bugs in lintr triggered by malformed code (e.g. https://github.com/jimhester/lintr/issues/461). In https://github.com/REditorSupport/languageserver/pull/220, we make all such lintr failure explicit or otherwise the diagnostics will be silently no error as the background process ends up in an error without any lintr result.

Would you like to reduce your document and find the minimal content that could reproduce such error?

**Comment by gowerc** [comment]
Just to add that you can see if it is lintr (rather than the vscode extension) by manually calling lintr  yourself

(from the R console)
```
library(lintr)
lint("./path_to_file/file_to_lint.R")
```

**Comment by nathaneastwood** [comment]
```r
lint("./R/select.R")                                                                                                                                          
# Error in linters[[linter]](expr) : attempt to apply non-function
```

Interesting. I have a valid `.lintr` file, and I tried reinstalling `lintr` but no joy. How very odd.

**Comment by nathaneastwood** [comment]
FYI, I had some issues with the `withr` file was corrupt telling me that `withr.rdb` was corrupt. I deleted the package and managed to install the latest version of `lintr` from GitHub along with a new version of `lintr` but I still get this same issue so it can't be that.

**Comment by renkun-ken** [comment]
If your lintr works with other scripts but this one, it is then most likely to be caused by some lintr bug trying to deal with malformed code.

Would you like to try `parse("./R/select.R")` and see if the code could be parsed without an error?

And would you like to experiment by reducing code blocks in `./R/select.R` and see what's the minimal code block that could reproduce this error?

**Comment by nathaneastwood** [comment]
Ah this is a problem with every file in my package, sorry. It's not just one file playing up, this happens every time I open a .R file, it tries to run `lintr` against it but I get the diagnostic error I showed in my initial post. I will try to parse the script when I get a chance later and let you know how I get on.

**Comment by nathaneastwood** [comment]
FYI there were no issues parsing the file, nor any other files.

**Comment by gowerc** [comment]
Not sure what a solution is but you can disable lintr to suppress the error message I think by setting this setting in your json settings file :

```
"r.lsp.diagnostics": false
```

**Comment by renkun-ken** [comment]
@nathaneastwood Would you like to use the following to show the traceback:

```r
options(error = function() traceback(3))
```

and see what happens when you run `lint("./R/select.R")`.

It looks like your `.lintr` is not really valid I guess?

**Comment by nathaneastwood** [comment]
Ok, so I decided to delete my `.lintr` file and recreate it. Now it would appear to be working. I know I tried this the other day with no joy so I am wondering if between the reinstallation of `lintr` and the recreation of the `.lintr` file it has been solved. I cannot pinpoint the solution exactly but thank you very much for your suggestions!

I now have another issue where functions defined within my package (and therefore my VSCode workspace) are not being detected.

```
no visible global function definition for '...' object_usage_linter
```

where `...` here represents the several functions which show this. Any thoughts? (I've tried both `library()` and `devtools::load_all()`)

**Comment by renkun-ken** [comment]
@nathaneastwood The `object_usage_linter` seems problematic, see https://github.com/jimhester/lintr/issues/482.

**Comment by nathaneastwood** [comment]
Ah, no problem. Let's close this issue for now then. Thanks very much for all your help.

**Comment by DrakoPOD** [comment]
> Ok, so I decided to delete my `.lintr` file and recreate it. Now it would appear to be working. I know I tried this the other day with no joy so I am wondering if between the reinstallation of `lintr` and the recreation of the `.lintr` file it has been solved. I cannot pinpoint the solution exactly but thank you very much for your suggestions!

Can you provide the settings in your `.lintr`? I already tryed what you said, but I still get the same error:

```
Failed to run diagnostics: ! in callr subprocess.
Caused by error: 
! Full file exclusions must be character vectors of length 1. items: 1 are not! lintr
```

**Comment by nathaneastwood** [comment]
Unfortunately I no longer have access to the laptop I had this issue on, sorry.

**Comment by Falven** [comment]
Happens with:
```
linters: linters_with_defaults() # see vignette("lintr")
encoding: "UTF-8"
```
and a jupyter notebook.

**Comment by Falven** [comment]
I noticed for R Jupyter notebooks it happens whenever you have a comment that exceeds the gutter size. If you break up the long comments into multiple lines, the errors go away.

**Comment by kdzhang** [comment]
Probably related to https://github.com/REditorSupport/vscode-R/issues/1198

**Comment by cworld1** [comment]
> I noticed for R Jupyter notebooks it happens whenever you have a comment that exceeds the gutter size. If you break up the long comments into multiple lines, the errors go away.

But it also shows as I assign any variable:

![image](https://user-images.githubusercontent.com/37377181/231619363-77410515-c8ab-4974-8d43-bcd737e4037f.png)

Or just one small comment:

![image](https://user-images.githubusercontent.com/37377181/231619483-973cfdb2-af39-40a8-8c13-b02f4af2ec3b.png)

It looks in a mess and I just follow the `.lintr` file creation, and nothing have made any change on that.

**Comment by renkun-ken** [comment]
Should be fixed via https://github.com/REditorSupport/languageserver/pull/610.

**Comment by cworld1** [comment]
Thank you! It works very well!

If there's anybody find it wrong like me, just try update languageserver package using the latest development build below:

```r
install.packages("languageserver", repos = c(
    reditorsupport = "https://reditorsupport.r-universe.dev",
    getOption("repos")
))
```

**Comment by matthutchings** [comment]
I am having the same issue as @cworld1, as in the first variable I declare or the first function I call in a notebook cell, I get `Failed to run diagnostics: ! in callr subprocess`. This is however caused by a different error: `! object 'R_user_dir' is not exported by 'namespace:tools' lintr`.

![image](https://github.com/REditorSupport/vscode-R/assets/16624586/cb501bb7-2a65-4c11-bb66-91c9788c0d2b)

This also happens in a .R file, but running `lintr::lint` on this file in a terminal gives no issues.

I have tried both deleting `.lintr` and regenerating it with `lintr::use_lint()`, but no luck.

`languageserver` version is 0.3.15 and `lintr` version is 3.0.2.

**Comment by renkun-ken** [comment]
@matthutchings Would you like to try the latest development version of languageserver via 


```r
install.packages("languageserver", repos = c(
    reditorsupport = "https://reditorsupport.r-universe.dev",
    getOption("repos")
))
```

**Comment by matthutchings** [comment]
Sorry @renkun-ken, I should have mentioned that I have already tried installing the latest dev version.

**Comment by KatlehoJordan** [comment]
After installing the latest version of the language server, I am still having this issue:

![image](https://github.com/REditorSupport/vscode-R/assets/89082001/e71671e0-b381-4219-9b33-f6f9ec417d77)


I'm running r in a jupyter notebook on a VS Code dev container.

<html>
<body>


CPUs | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 7.90GB (0.63GB free)
Process Argv | ds-playground/ --crash-reporter-id 0035e842-412c-44d1-a8d3-4d2b52fb8945
Screen Reader | no
VM | 0%


</body>
</html>


<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
vscode-neovim | asv | 0.0.97
vscode-drawio | hed | 1.6.6
jupyter-keymap | ms- | 1.1.2
remote-containers | ms- | 0.295.0
pdf | tom | 1.2.2
vscode-icons | vsc | 12.4.0
black-formatter | ms- | 2023.2.0
isort | ms- | 2022.8.0
pylint | ms- | 2023.4.0
python | ms- | 2023.10.1
vscode-pylance | ms- | 2023.6.21
jupyter | ms- | 2023.5.1001582324
jupyter-keymap | ms- | 1.1.2
jupyter-renderers | ms- | 1.0.15
vscode-jupyter-cell-tags | ms- | 0.1.8
vscode-jupyter-slideshow | ms- | 0.1.5
autodocstring | njp | 0.6.1
r-debugger | RDe | 0.5.4
r | REd | 2.8.1
intellicode-api-usage-examples | Vis | 0.2.7
vscodeintellicode | Vis | 1.2.30


</body>
</html>

**Comment by benz0li** [comment]
> Would you like to try the latest development version of languageserver via
> 
> ```r
> install.packages("languageserver", repos = c(
>     reditorsupport = "https://reditorsupport.r-universe.dev",
>     getOption("repos")
> ))
> ```

I tried. It resolves the issue

```
Failed to run diagnostics: ! in callr subprocess.
Caused by error: 
! Linter 'object_length_linter' failed in : path[1]="": No such file or directory
```

I had when working with Jupyter Notebooks.

---

@renkun-ken Will there soon be an updated version on CRAN or should I install from R-universe until further notice?

**Comment by osmano807** [comment]
I'm still affected by this issue using rev 1e71561a41ef59126273f16bbb466c0b30a2aa64 with a Windows VSCode and Linux Jupyter Lab server.

**Comment by Tal500** [comment]
@renkun-ken I want to mention the same error happens to me when I browsing GIt diff of a file in VSCode UI.
It seems that for such diff files view, the URI that is given to the languageserver of this "file" is of the form "git:PATH?{%22path%22:%22PATH%%22,%22ref%22:%22HEAD%22}". Probably the lintr package raise errors for such paths.

**Comment by scholarazwa** [comment]
If you have issues with .linter file not being recognised, what works for me is:
- In your .linter file, after making sure the last bracket is next to the last line of options and added a newline to the end of the file, save it as UTF-8. In Sublime Text there is an option 'Reopen with Encoding', then choose UTF-8 then save the .linter file. It should now work.

**Comment by gonzarizzo** [comment]
> I have the same issue running vscode on a conda environment created in Debian running on WSL.
> 
> ![image](https://user-images.githubusercontent.com/97065192/254381212-4085921a-40a0-4480-9a30-803973ded237.png)
> 
> The problem is caused in a file.R.git
> 
> ![image](https://user-images.githubusercontent.com/97065192/254381768-04677ee7-5293-4aed-9b56-84df057a6a85.png)
> 
> Could you make the developer version available through conda-forge?
> 
> Thank you, Gonzalo

I have solved this issue by adding .R.git files to the files exclusions.

To do so you have to follow the next steps:

1. Open visual studio code
2. Click Settings icon in the left bottom and click `Settings`
3. In the search box, search for `Files: Associations` (Copy-paste this)
4. Click [Add Item] button and enter `**/*.R.git` for key, `text` for value.

This is how it looks:

![image](https://github.com/REditorSupport/vscode-R/assets/97065192/a89f0d48-bad1-48a4-a1ef-facb208da9e3)


You can add the following lines to your settings.json file, and will have the same results.

```
"files.associations": {
        "**/*.R.git": ""
    }
```
